name: PluginBase
version: '${version}'
main: org.apo.pluginbase.PluginBase
api-version: '1.20'
commands:
  base:
    description: plugin base command
    permission: base.base
    aliases:
      - bs
permissions:
  base.*:
    description: Base Plugin permissions
    base.base : true
    default: op